name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.tarkesh852 }}
          password: ${{ secrets.tarkesh@12345 }}

      - name: Build Docker image
        run: docker build . -t tarkesh852/myapp:latest

      - name: Push Docker image
        run: docker push tarkesh852/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: SSH into server and deploy
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "docker-compose.yml"
          target: "/path/to/your/app"

      - name: Pull and deploy new image
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /path/to/your/app
          docker-compose pull
          docker-compose up -d
          EOF
