name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.tarkesh@12345 }}" | docker login -u "${{ tarkesh852 }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t my-image:latest

      - name: Push Docker image
        run: docker push my-image:latest
