name: Docker Login and Push

on:
  push:
    branches:
      - main

jobs:
  docker_login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.tarkesh852 }}
          password: ${{ secrets.tarkesh@12345 }}
          ecr: auto
          logout: true

      - name: Build Docker image
        run: docker build . -t tarkesh852/myapp:latest

      - name: Push Docker image
        run: docker push tarkesh852/myapp:latest
